### ISSUE TITLE
画图函数

### ISSUE THREAD

**Issue by alibabazzz999** [cathaypacific8747/mu5735#1]
打扰了，怎么进行轨迹展示的呢，没在你的代码里体现，谢谢

**Comment by abc8747** [comment]
This project does not generate the images for the flight track - it only converts the granular CSV data provided by flightradar24 to a [KML file](https://en.wikipedia.org/wiki/Keyhole_Markup_Language), which is a file format recognised by many GIS applications. You can browse the flight path in 3D using tools such as [Google Earth](https://earth.google.com/web/) or [QGIS](https://www.qgis.org).

The KML file can be downloaded under the [Releases](https://github.com/cathaypacific8747/mu5735/releases).
